devguider:
  greeting: "반갑습니다"

---
spring:
  profiles: stg
devguider:  
  greeting: "스테이징 서버입니다"

---
spring:
  profiles: dev
devguider:  
  greeting: "개발 서버입니다"

---
spring:
  profiles: prod
devguider:  
  greeting: "프로드 서버입니다/^0^/"
